### ISSUE TITLE
Clay Golem Precast Issue

### ISSUE THREAD

**Issue by jcreynolds** [Borega/pd2bs-scripts#1]
My Golem Mastery isn't high enough to have more then 1 golem.  Bot almost (I say almost because it does stutter step, and if by chance mobs are around it does kill them) endlessly casts Clay Golem.

**Comment by Borega** [comment]
A check for Skill level is needed. What are the steps when u can cast more than one golem?
2 Golem on lvl =?
3 Golem on lvl=? 
Same goes for the amazon and firegolems.

**Comment by jcreynolds** [comment]
Line 403 - Is that not what this is doing?  Checking Golem Mastery level?
`			
case 75: // Clay Golem
				var mastery = me.getSkill(79, 1);
				
				if (mastery >= 5 && mastery < 10 ) {
					count = 2;
				}
				else if (mastery >= 10 && mastery < 15) {
					count = 3;
				}
				else if (mastery >= 15 && mastery < 20) {
					count = 4;
				}
				else if (mastery >= 20) {
					count = 5;
				}	
				else {
					count = 1;
				}		`

My Golem Mastery is at 8.

**Comment by Borega** [comment]
I think the Minion variable was missing. pls look if it works now

**Comment by jcreynolds** [comment]
Nope still does it endlessly.

**Comment by jcreynolds** [comment]
![image](https://user-images.githubusercontent.com/20443470/111512860-32718080-871e-11eb-85b2-9a24e55fcf91.png)

**Comment by jcreynolds** [comment]
The ranges are not correct.  Thats seems to be because the skill isn't granting correct amount of golems as per the wiki.  At level 10 you should be able to summon 3 golems.  At 10 I can only summon 2:

![image](https://user-images.githubusercontent.com/20443470/111517049-a44bc900-8722-11eb-9236-b8be5362a4df.png)

Edit:  Ahh its based upon base levels.  I have +5 summon skills.  So the precast mastery is probably returning 10, expecting the ability to summon 3 golems.  In reality I am a base level 5, and can only summon 2.  For the time being until I level more and can get more skill points to test this I am going to hard code 2 golems.

**Comment by yayza** [comment]
I think minion was already getting set from case 94? Anyway until someone figures out how to get base skill with +item additions it's probably cleaner to just set it to a value from char config file.  Something like

```		
case 75: // Clay Golem			
case 85: // Blood Golem
case 94: // Fire Golem
      if(Config.GolemCount){
           count = Config.GolemCount;
        }
	minion = 3;
break;
```

and just add `Config.GolemCount = 2` in your char config.

**Comment by yayza** [comment]
Fixed in https://github.com/Borega/pd2bs-scripts/commit/a0c572d6baa1d9f22046e6e79799efaff4f63385
