### ISSUE TITLE
Setting LesserHydra/Hydra as timed skill causes bot to constantly cast Hydra instead of waiting for them to run out

### ISSUE THREAD

**Issue by nimbusdin** [Borega/pd2bs-scripts#14]
Setting Hydra/Lesser Hydra as a timed skill causes the bot to use it as an untimed skill, constantly casting it even when the max number of hydras are already out.

**Comment by yayza** [comment]
Thanks for bringing this up. I removed the hydra skills from Misc.js . Try adding them to your attack config and untimed or primary skills and see if she still spams them. I might have to add a counter for them to to only cast if theres less than three.

**Comment by Borega** [comment]
I solved that last league by putting it into precast in the attack config and adding a function to tripplecast there. might be able to look into it today.

**Comment by Yolobearmon** [comment]
Would love to see this working, would be a great improvement for sorc's in general.

**Comment by Borega** [comment]
hydra is fixed

**Comment by Borega** [comment]
Now also using lesser hydra if that is the only option available
