### ISSUE TITLE
Starting more than one profile/client at once is forcing "wrong version" ingame.

### ISSUE THREAD

**Issue by Yolobearmon** [Borega/pd2bs-scripts#16]
Like topic says, if starting more than 1 profile/client at once it forces wrong version ingame and causes connection interruped over and over. This is sorted by just opening 1 and then waiting a few seconds to open the next, but kinda destroys "scheduling" after a realm restart etc. I did try alot of potential fixes people suggested, however with no luck.

**Comment by Borega** [comment]
this is a d2bs and d2bot issue.
