### ISSUE TITLE
Account for stacked runes when creating Runewords

### ISSUE THREAD

**Issue by drwhooo252** [Borega/pd2bs-scripts#17]
As the title says
Needs to account for stacked rune IDs
When found and have all runes for RW, unstack needed rune

**Comment by yayza** [comment]
This has been added in the latest commits

Update your kolbot folder
Set this to true.
`Config.MakeRunewords = true; // Set to true to enable runeword making/rerolling`

Example runeword addition
`Config.Runewords.push([Runeword.Fortitude, "Archon Plate"]);`
Pretty much unchanged config settings from the original kolbot, only now, thanks to @Azur3Sky, if you have the required runes in stacks, it'll automatically unstack them and create the runeword for you.
