### ISSUE TITLE
Precast.js - Sorceress Cold Enchant

### ISSUE THREAD

**Issue by potato-T** [Borega/pd2bs-scripts#6]
Missing Cold Enchant skill for sorceress precast list (new skills)

**Comment by Tektic** [comment]
Precast.js line 438 (I made a bunch of changes your line might be different)

`		if (unit) {
			do {
				if (!unit.dead && Misc.inMyParty(unit.name) && getDistance(me, unit) <= 40) {
					Skill.cast(52, 0, unit);
					Skill.cast(40, 0, unit);
					chanted.push(unit.name);
				}
			} while (unit.getNext());
		}`

**Comment by yayza** [comment]
https://github.com/Borega/pd2bs-scripts/commit/aa5631b252acf9c247cf6169d7410eb4b6fb97dc
